### ISSUE TITLE
Firebase error

### ISSUE THREAD

**Issue by ArhumJain** [The-6th-Champion/lessinsert-bot-heregreater#2]
```e1: Could not load cog cogs.funclone:Extension 'cogs.funclone' raised an error: ValueError: The default Firebase app already exists. This means you called initialize_app() more than once without providing an app name as the second argument. In most cases you only need to call initialize_app() once. But if you do want to initialize multiple apps, pass a second argument to initialize_app() to give each app a unique name.```

Firebase initialization is bugged.

**Comment by AdityaJain1030** [comment]
You be initing twice
Call it once and export the app in a variable
